In [8]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline

In [9]:
df=pd.read_csv('./data/stud.csv')

In [10]:
df.head()

,gender,race_ethnicity,parental_level_of_education,lunch,test_preparation_course,math_score,reading_score,writing_score
0,female,group B,bachelor's degree,standard,none,72,72,74
1,female,group C,some college,standard,completed,69,90,88
2,female,group B,master's degree,standard,none,90,95,93
3,male,group A,associate's degree,free/reduced,none,47,57,44
4,male,group C,some college,standard,none,76,78,75

In [11]:
df.isnull().sum()

gender                         0
race_ethnicity                 0
parental_level_of_education    0
lunch                          0
test_preparation_course        0
math_score                     0
reading_score                  0
writing_score                  0
dtype: int64

In [12]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 8 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   gender                       1000 non-null   object
 1   race_ethnicity               1000 non-null   object
 2   parental_level_of_education  1000 non-null   object
 3   lunch                        1000 non-null   object
 4   test_preparation_course      1000 non-null   object
 5   math_score                   1000 non-null   int64
 6   reading_score                1000 non-null   int64
 7   writing_score                1000 non-null   int64
dtypes: int64(3), object(5)
memory usage: 62.6+ KB

In [13]:
df.duplicated().sum()

np.int64(0)

In [14]:
df.nunique()

gender                          2
race_ethnicity                  5
parental_level_of_education     6
lunch                           2
test_preparation_course         2
math_score                     81
reading_score                  72
writing_score                  77
dtype: int64

In [15]:
df.describe()

       math_score  reading_score  writing_score
count  1000.00000    1000.000000    1000.000000
mean     66.08900      69.169000      68.054000
std      15.16308      14.600192      15.195657
min       0.00000      17.000000      10.000000
25%      57.00000      59.000000      57.750000
50%      66.00000      70.000000      69.000000
75%      77.00000      79.000000      79.000000
max     100.00000     100.000000     100.000000

In [16]:
# fing numarical and catogorical columns
num_features=[feature for feature in df.columns if df[feature].dtype!='O']
cat_features=[feature for feature in df.columns if df[feature].dtype=='O']
print("numarical features = ",num_features)
print("catogorical features",cat_features)

numarical features =  ['math_score', 'reading_score', 'writing_score']
catogorical features ['gender', 'race_ethnicity', 'parental_level_of_education', 'lunch', 'test_preparation_course']

In [17]:
df.head()

,gender,race_ethnicity,parental_level_of_education,lunch,test_preparation_course,math_score,reading_score,writing_score
0,female,group B,bachelor's degree,standard,none,72,72,74
1,female,group C,some college,standard,completed,69,90,88
2,female,group B,master's degree,standard,none,90,95,93
3,male,group A,associate's degree,free/reduced,none,47,57,44
4,male,group C,some college,standard,none,76,78,75

In [18]:
# adding a column that has total score
df['Total_score']=df['math_score']+df["reading_score"]+df["writing_score"]
df['average']=df['Total_score']/3

In [19]:
df.head()

,gender,race_ethnicity,parental_level_of_education,lunch,test_preparation_course,math_score,reading_score,writing_score,Total_score,average
0,female,group B,bachelor's degree,standard,none,72,72,74,218,72.666667
1,female,group C,some college,standard,completed,69,90,88,247,82.333333
2,female,group B,master's degree,standard,none,90,95,93,278,92.666667
3,male,group A,associate's degree,free/reduced,none,47,57,44,148,49.333333
4,male,group C,some college,standard,none,76,78,75,229,76.333333

In [20]:
df.nunique()

gender                           2
race_ethnicity                   5
parental_level_of_education      6
lunch                            2
test_preparation_course          2
math_score                      81
reading_score                   72
writing_score                   77
Total_score                    194
average                        194
dtype: int64

In [21]:
x=df.drop('math_score',axis=1)
y=df['math_score']

In [22]:
from sklearn.preprocessing import StandardScaler,OneHotEncoder
from sklearn.compose import ColumnTransformer

In [23]:
cat_features=x.select_dtypes(include="object").columns
num_features=x.select_dtypes(exclude="object").columns
scalar=StandardScaler()
encoder=OneHotEncoder()
preprocesser=ColumnTransformer(
    [("OneHotEncoder",encoder,cat_features),
    ("StandardScaler",scalar,num_features)
    ]
)

In [24]:
cat_features

Index(['gender', 'race_ethnicity', 'parental_level_of_education', 'lunch',
       'test_preparation_course'],
      dtype='object')

In [25]:
x=preprocesser.fit_transform(x)

In [35]:
x.shape

(1000, 21)

In [27]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)

In [28]:
!pip install xgboost

Requirement already satisfied: xgboost in c:\users\jagad\anaconda3\lib\site-packages (3.1.3)
Requirement already satisfied: numpy in c:\users\jagad\anaconda3\lib\site-packages (from xgboost) (2.3.5)
Requirement already satisfied: scipy in c:\users\jagad\anaconda3\lib\site-packages (from xgboost) (1.16.3)

In [29]:
!pip install catboost

Requirement already satisfied: catboost in c:\users\jagad\anaconda3\lib\site-packages (1.2.8)
Requirement already satisfied: graphviz in c:\users\jagad\anaconda3\lib\site-packages (from catboost) (0.21)
Requirement already satisfied: matplotlib in c:\users\jagad\anaconda3\lib\site-packages (from catboost) (3.10.6)
Requirement already satisfied: numpy<3.0,>=1.16.0 in c:\users\jagad\anaconda3\lib\site-packages (from catboost) (2.3.5)
Requirement already satisfied: pandas>=0.24 in c:\users\jagad\anaconda3\lib\site-packages (from catboost) (2.3.3)
Requirement already satisfied: scipy in c:\users\jagad\anaconda3\lib\site-packages (from catboost) (1.16.3)
Requirement already satisfied: plotly in c:\users\jagad\anaconda3\lib\site-packages (from catboost) (6.3.0)
Requirement already satisfied: six in c:\users\jagad\anaconda3\lib\site-packages (from catboost) (1.17.0)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\jagad\anaconda3\lib\site-packages (from pandas>=0.24->catboost) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\jagad\anaconda3\lib\site-packages (from pandas>=0.24->catboost) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\jagad\anaconda3\lib\site-packages (from pandas>=0.24->catboost) (2025.2)
Requirement already satisfied: contourpy>=1.0.1 in c:\users\jagad\anaconda3\lib\site-packages (from matplotlib->catboost) (1.3.3)
Requirement already satisfied: cycler>=0.10 in c:\users\jagad\anaconda3\lib\site-packages (from matplotlib->catboost) (0.11.0)
Requirement already satisfied: fonttools>=4.22.0 in c:\users\jagad\anaconda3\lib\site-packages (from matplotlib->catboost) (4.60.1)
Requirement already satisfied: kiwisolver>=1.3.1 in c:\users\jagad\anaconda3\lib\site-packages (from matplotlib->catboost) (1.4.9)
Requirement already satisfied: packaging>=20.0 in c:\users\jagad\anaconda3\lib\site-packages (from matplotlib->catboost) (25.0)
Requirement already satisfied: pillow>=8 in c:\users\jagad\anaconda3\lib\site-packages (from matplotlib->catboost) (12.0.0)
Requirement already satisfied: pyparsing>=2.3.1 in c:\users\jagad\anaconda3\lib\site-packages (from matplotlib->catboost) (3.2.5)
Requirement already satisfied: narwhals>=1.15.1 in c:\users\jagad\anaconda3\lib\site-packages (from plotly->catboost) (2.7.0)

In [30]:
from sklearn.linear_model import LinearRegression,Lasso,Ridge
from sklearn.neighbors import KNeighborsRegressor
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor
from sklearn.ensemble import AdaBoostRegressor
from xgboost import XGBRegressor
from catboost import CatBoostRegressor

In [33]:
from sklearn.metrics import accuracy_score,r2_score

In [34]:
models={
    "LinearRegression": LinearRegression(),
    "Lasso": Lasso(), 
    "Ridge": Ridge(), 
    "KNN": KNeighborsRegressor(), 
    "DecisionTree": DecisionTreeRegressor(), 
    "RandomForest": RandomForestRegressor(), 
    "AdaBoost": AdaBoostRegressor(), 
    "XGB": XGBRegressor(), 
    "CatBoost": CatBoostRegressor()
}
for i in models:
    model=models.get(i)
    model.fit(x_train,y_train)
    y_pred=model.predict(x_test)
    print("accuracy for ",i," ",r2_score(y_test,y_pred))

accuracy for  LinearRegression   1.0
accuracy for  Lasso   0.9085602868908693
accuracy for  Ridge   0.9995159680022121
accuracy for  KNN   0.889781473043301
accuracy for  DecisionTree   0.9362205060935718
accuracy for  RandomForest   0.9628859522377068
accuracy for  AdaBoost   0.9268617874615743
accuracy for  XGB   0.9771012663841248
Learning rate set to 0.039525
0:	learn: 14.5699294	total: 139ms	remaining: 2m 18s
1:	learn: 14.1482535	total: 142ms	remaining: 1m 10s
2:	learn: 13.7141716	total: 143ms	remaining: 47.7s
3:	learn: 13.3002481	total: 145ms	remaining: 36.1s
4:	learn: 12.9328569	total: 147ms	remaining: 29.2s
5:	learn: 12.5771090	total: 149ms	remaining: 24.8s
6:	learn: 12.2061520	total: 152ms	remaining: 21.5s
7:	learn: 11.8772700	total: 153ms	remaining: 19s
8:	learn: 11.5375927	total: 155ms	remaining: 17.1s
9:	learn: 11.2013867	total: 157ms	remaining: 15.5s
10:	learn: 10.8965503	total: 158ms	remaining: 14.2s
11:	learn: 10.5991681	total: 160ms	remaining: 13.2s
12:	learn: 10.3321148	total: 162ms	remaining: 12.3s
13:	learn: 10.0697012	total: 164ms	remaining: 11.5s
14:	learn: 9.8244261	total: 166ms	remaining: 10.9s
15:	learn: 9.5723500	total: 168ms	remaining: 10.3s
16:	learn: 9.3544998	total: 170ms	remaining: 9.81s
17:	learn: 9.1611238	total: 171ms	remaining: 9.33s
18:	learn: 8.9614039	total: 173ms	remaining: 8.93s
19:	learn: 8.7345763	total: 175ms	remaining: 8.57s
20:	learn: 8.5116664	total: 177ms	remaining: 8.23s
21:	learn: 8.3068515	total: 178ms	remaining: 7.92s
22:	learn: 8.1105456	total: 180ms	remaining: 7.64s
23:	learn: 7.9244605	total: 182ms	remaining: 7.39s
24:	learn: 7.7439026	total: 184ms	remaining: 7.16s
25:	learn: 7.5640688	total: 185ms	remaining: 6.93s
26:	learn: 7.4042159	total: 186ms	remaining: 6.71s
27:	learn: 7.2564386	total: 188ms	remaining: 6.53s
28:	learn: 7.1060815	total: 190ms	remaining: 6.35s
29:	learn: 6.9605968	total: 191ms	remaining: 6.19s
30:	learn: 6.8137531	total: 193ms	remaining: 6.03s
31:	learn: 6.6868119	total: 194ms	remaining: 5.88s
32:	learn: 6.5610859	total: 196ms	remaining: 5.75s
33:	learn: 6.4372644	total: 198ms	remaining: 5.63s
34:	learn: 6.3209332	total: 200ms	remaining: 5.5s
35:	learn: 6.2199602	total: 201ms	remaining: 5.38s
36:	learn: 6.1213295	total: 203ms	remaining: 5.28s
37:	learn: 6.0256257	total: 204ms	remaining: 5.17s
38:	learn: 5.9181128	total: 206ms	remaining: 5.07s
39:	learn: 5.8297210	total: 207ms	remaining: 4.98s
40:	learn: 5.7503810	total: 209ms	remaining: 4.89s
41:	learn: 5.6702476	total: 211ms	remaining: 4.81s
42:	learn: 5.5849161	total: 213ms	remaining: 4.73s
43:	learn: 5.4974914	total: 214ms	remaining: 4.65s
44:	learn: 5.4177670	total: 215ms	remaining: 4.57s
45:	learn: 5.3483978	total: 217ms	remaining: 4.5s
46:	learn: 5.2721565	total: 218ms	remaining: 4.43s
47:	learn: 5.2072251	total: 220ms	remaining: 4.36s
48:	learn: 5.1478671	total: 222ms	remaining: 4.3s
49:	learn: 5.0874909	total: 223ms	remaining: 4.24s
50:	learn: 5.0221999	total: 225ms	remaining: 4.18s
51:	learn: 4.9678096	total: 226ms	remaining: 4.13s
52:	learn: 4.9095509	total: 229ms	remaining: 4.09s
53:	learn: 4.8588674	total: 231ms	remaining: 4.04s
54:	learn: 4.8122920	total: 232ms	remaining: 3.99s
55:	learn: 4.7575565	total: 234ms	remaining: 3.94s
56:	learn: 4.7086203	total: 235ms	remaining: 3.9s
57:	learn: 4.6620542	total: 238ms	remaining: 3.87s
58:	learn: 4.6191885	total: 240ms	remaining: 3.83s
59:	learn: 4.5874961	total: 242ms	remaining: 3.79s
60:	learn: 4.5480624	total: 243ms	remaining: 3.75s
61:	learn: 4.5082055	total: 245ms	remaining: 3.71s
62:	learn: 4.4764161	total: 247ms	remaining: 3.67s
63:	learn: 4.4405233	total: 249ms	remaining: 3.63s
64:	learn: 4.4064768	total: 250ms	remaining: 3.59s
65:	learn: 4.3719812	total: 252ms	remaining: 3.56s
66:	learn: 4.3417383	total: 254ms	remaining: 3.54s
67:	learn: 4.3127211	total: 256ms	remaining: 3.5s
68:	learn: 4.2849665	total: 257ms	remaining: 3.47s
69:	learn: 4.2530037	total: 259ms	remaining: 3.44s
70:	learn: 4.2229462	total: 260ms	remaining: 3.41s
71:	learn: 4.1952504	total: 262ms	remaining: 3.37s
72:	learn: 4.1723439	total: 263ms	remaining: 3.34s
73:	learn: 4.1474703	total: 265ms	remaining: 3.31s
74:	learn: 4.1267312	total: 266ms	remaining: 3.28s
75:	learn: 4.1065437	total: 268ms	remaining: 3.26s
76:	learn: 4.0790861	total: 270ms	remaining: 3.24s
77:	learn: 4.0626445	total: 272ms	remaining: 3.21s
78:	learn: 4.0381700	total: 274ms	remaining: 3.19s
79:	learn: 4.0199051	total: 275ms	remaining: 3.16s
80:	learn: 4.0031056	total: 276ms	remaining: 3.14s
81:	learn: 3.9827572	total: 278ms	remaining: 3.11s
82:	learn: 3.9647070	total: 279ms	remaining: 3.09s
83:	learn: 3.9483148	total: 282ms	remaining: 3.07s
84:	learn: 3.9286507	total: 283ms	remaining: 3.05s
85:	learn: 3.9125679	total: 285ms	remaining: 3.03s
86:	learn: 3.8981495	total: 286ms	remaining: 3s
87:	learn: 3.8815025	total: 288ms	remaining: 2.98s
88:	learn: 3.8685980	total: 289ms	remaining: 2.96s
89:	learn: 3.8542517	total: 291ms	remaining: 2.94s
90:	learn: 3.8382728	total: 292ms	remaining: 2.92s
91:	learn: 3.8249521	total: 294ms	remaining: 2.9s
92:	learn: 3.8075675	total: 296ms	remaining: 2.89s
93:	learn: 3.7909678	total: 298ms	remaining: 2.87s
94:	learn: 3.7829130	total: 299ms	remaining: 2.85s
95:	learn: 3.7742016	total: 301ms	remaining: 2.84s
96:	learn: 3.7627424	total: 303ms	remaining: 2.82s
97:	learn: 3.7510711	total: 304ms	remaining: 2.8s
98:	learn: 3.7387753	total: 305ms	remaining: 2.78s
99:	learn: 3.7233839	total: 307ms	remaining: 2.77s
100:	learn: 3.7071186	total: 309ms	remaining: 2.75s
101:	learn: 3.6994931	total: 310ms	remaining: 2.73s
102:	learn: 3.6886745	total: 312ms	remaining: 2.72s
103:	learn: 3.6793514	total: 315ms	remaining: 2.71s
104:	learn: 3.6718882	total: 316ms	remaining: 2.69s
105:	learn: 3.6588442	total: 317ms	remaining: 2.68s
106:	learn: 3.6489878	total: 319ms	remaining: 2.66s
107:	learn: 3.6365755	total: 320ms	remaining: 2.64s
108:	learn: 3.6226602	total: 322ms	remaining: 2.63s
109:	learn: 3.6144382	total: 323ms	remaining: 2.61s
110:	learn: 3.6016861	total: 325ms	remaining: 2.6s
111:	learn: 3.5901519	total: 327ms	remaining: 2.59s
112:	learn: 3.5783231	total: 328ms	remaining: 2.58s
113:	learn: 3.5604749	total: 330ms	remaining: 2.56s
114:	learn: 3.5495848	total: 331ms	remaining: 2.55s
115:	learn: 3.5426194	total: 333ms	remaining: 2.54s
116:	learn: 3.5365474	total: 335ms	remaining: 2.53s
117:	learn: 3.5234126	total: 337ms	remaining: 2.52s
118:	learn: 3.5133331	total: 339ms	remaining: 2.51s
119:	learn: 3.5069918	total: 341ms	remaining: 2.5s
120:	learn: 3.5001363	total: 343ms	remaining: 2.49s
121:	learn: 3.4914783	total: 345ms	remaining: 2.48s
122:	learn: 3.4801818	total: 347ms	remaining: 2.48s
123:	learn: 3.4719160	total: 349ms	remaining: 2.47s
124:	learn: 3.4607505	total: 351ms	remaining: 2.46s
125:	learn: 3.4537657	total: 353ms	remaining: 2.45s
126:	learn: 3.4473538	total: 354ms	remaining: 2.44s
127:	learn: 3.4395003	total: 357ms	remaining: 2.43s
128:	learn: 3.4315541	total: 359ms	remaining: 2.42s
129:	learn: 3.4258762	total: 361ms	remaining: 2.42s
130:	learn: 3.4209766	total: 364ms	remaining: 2.41s
131:	learn: 3.4148524	total: 366ms	remaining: 2.4s
132:	learn: 3.4085772	total: 367ms	remaining: 2.4s
133:	learn: 3.4029211	total: 370ms	remaining: 2.39s
134:	learn: 3.3955123	total: 371ms	remaining: 2.38s
135:	learn: 3.3879265	total: 373ms	remaining: 2.37s
136:	learn: 3.3809167	total: 375ms	remaining: 2.36s
137:	learn: 3.3696210	total: 377ms	remaining: 2.35s
138:	learn: 3.3594178	total: 378ms	remaining: 2.34s
139:	learn: 3.3495777	total: 380ms	remaining: 2.33s
140:	learn: 3.3443176	total: 382ms	remaining: 2.32s
141:	learn: 3.3339747	total: 383ms	remaining: 2.31s
142:	learn: 3.3255941	total: 384ms	remaining: 2.3s
143:	learn: 3.3186494	total: 386ms	remaining: 2.29s
144:	learn: 3.3081765	total: 388ms	remaining: 2.29s
145:	learn: 3.3040613	total: 389ms	remaining: 2.27s
146:	learn: 3.2936216	total: 391ms	remaining: 2.27s
147:	learn: 3.2850409	total: 392ms	remaining: 2.26s
148:	learn: 3.2740599	total: 394ms	remaining: 2.25s
149:	learn: 3.2690457	total: 396ms	remaining: 2.24s
150:	learn: 3.2641445	total: 397ms	remaining: 2.23s
151:	learn: 3.2606637	total: 399ms	remaining: 2.22s
152:	learn: 3.2537051	total: 400ms	remaining: 2.21s
153:	learn: 3.2440838	total: 402ms	remaining: 2.21s
154:	learn: 3.2435525	total: 402ms	remaining: 2.19s
155:	learn: 3.2377367	total: 404ms	remaining: 2.18s
156:	learn: 3.2349633	total: 405ms	remaining: 2.17s
157:	learn: 3.2242465	total: 408ms	remaining: 2.17s
158:	learn: 3.2168512	total: 409ms	remaining: 2.16s
159:	learn: 3.2126312	total: 411ms	remaining: 2.15s
160:	learn: 3.2081246	total: 412ms	remaining: 2.15s
161:	learn: 3.1996451	total: 414ms	remaining: 2.14s
162:	learn: 3.1923302	total: 415ms	remaining: 2.13s
163:	learn: 3.1868404	total: 417ms	remaining: 2.13s
164:	learn: 3.1793182	total: 419ms	remaining: 2.12s
165:	learn: 3.1725588	total: 421ms	remaining: 2.11s
166:	learn: 3.1635226	total: 422ms	remaining: 2.1s
167:	learn: 3.1631721	total: 423ms	remaining: 2.09s
168:	learn: 3.1606941	total: 424ms	remaining: 2.09s
169:	learn: 3.1562488	total: 426ms	remaining: 2.08s
170:	learn: 3.1522872	total: 427ms	remaining: 2.07s
171:	learn: 3.1431291	total: 429ms	remaining: 2.06s
172:	learn: 3.1370624	total: 430ms	remaining: 2.06s
173:	learn: 3.1316925	total: 432ms	remaining: 2.05s
174:	learn: 3.1287298	total: 433ms	remaining: 2.04s
175:	learn: 3.1248032	total: 435ms	remaining: 2.04s
176:	learn: 3.1212774	total: 436ms	remaining: 2.03s
177:	learn: 3.1183661	total: 438ms	remaining: 2.02s
178:	learn: 3.1091979	total: 440ms	remaining: 2.02s
179:	learn: 3.1041810	total: 441ms	remaining: 2.01s
180:	learn: 3.0990551	total: 444ms	remaining: 2.01s
181:	learn: 3.0950391	total: 445ms	remaining: 2s
182:	learn: 3.0927425	total: 447ms	remaining: 2s
183:	learn: 3.0899403	total: 449ms	remaining: 1.99s
184:	learn: 3.0868851	total: 451ms	remaining: 1.99s
185:	learn: 3.0848518	total: 453ms	remaining: 1.98s
186:	learn: 3.0806390	total: 454ms	remaining: 1.97s
187:	learn: 3.0791352	total: 456ms	remaining: 1.97s
188:	learn: 3.0729092	total: 458ms	remaining: 1.97s
189:	learn: 3.0678975	total: 460ms	remaining: 1.96s
190:	learn: 3.0622201	total: 461ms	remaining: 1.95s
191:	learn: 3.0545288	total: 463ms	remaining: 1.95s
192:	learn: 3.0467375	total: 465ms	remaining: 1.95s
193:	learn: 3.0384397	total: 467ms	remaining: 1.94s
194:	learn: 3.0326244	total: 469ms	remaining: 1.94s
195:	learn: 3.0261725	total: 470ms	remaining: 1.93s
196:	learn: 3.0227317	total: 472ms	remaining: 1.92s
197:	learn: 3.0202502	total: 474ms	remaining: 1.92s
198:	learn: 3.0118516	total: 476ms	remaining: 1.92s
199:	learn: 3.0046747	total: 478ms	remaining: 1.91s
200:	learn: 3.0005087	total: 480ms	remaining: 1.91s
201:	learn: 2.9945534	total: 481ms	remaining: 1.9s
202:	learn: 2.9863303	total: 483ms	remaining: 1.9s
203:	learn: 2.9772555	total: 484ms	remaining: 1.89s
204:	learn: 2.9732905	total: 486ms	remaining: 1.88s
205:	learn: 2.9655046	total: 487ms	remaining: 1.88s
206:	learn: 2.9556460	total: 489ms	remaining: 1.87s
207:	learn: 2.9521532	total: 491ms	remaining: 1.87s
208:	learn: 2.9445044	total: 493ms	remaining: 1.86s
209:	learn: 2.9392090	total: 494ms	remaining: 1.86s
210:	learn: 2.9333484	total: 496ms	remaining: 1.85s
211:	learn: 2.9238486	total: 498ms	remaining: 1.85s
212:	learn: 2.9200757	total: 500ms	remaining: 1.85s
213:	learn: 2.9124409	total: 502ms	remaining: 1.84s
214:	learn: 2.9086988	total: 503ms	remaining: 1.84s
215:	learn: 2.9060892	total: 506ms	remaining: 1.83s
216:	learn: 2.9006388	total: 508ms	remaining: 1.83s
217:	learn: 2.8914548	total: 509ms	remaining: 1.83s
218:	learn: 2.8887958	total: 512ms	remaining: 1.82s
219:	learn: 2.8840920	total: 513ms	remaining: 1.82s
220:	learn: 2.8737787	total: 515ms	remaining: 1.81s
221:	learn: 2.8716001	total: 516ms	remaining: 1.81s
222:	learn: 2.8645291	total: 519ms	remaining: 1.81s
223:	learn: 2.8603113	total: 522ms	remaining: 1.81s
224:	learn: 2.8570445	total: 525ms	remaining: 1.81s
225:	learn: 2.8545786	total: 527ms	remaining: 1.8s
226:	learn: 2.8522065	total: 529ms	remaining: 1.8s
227:	learn: 2.8401470	total: 530ms	remaining: 1.79s
228:	learn: 2.8366590	total: 532ms	remaining: 1.79s
229:	learn: 2.8309900	total: 534ms	remaining: 1.79s
230:	learn: 2.8212438	total: 537ms	remaining: 1.79s
231:	learn: 2.8175959	total: 539ms	remaining: 1.78s
232:	learn: 2.8104305	total: 541ms	remaining: 1.78s
233:	learn: 2.8074363	total: 544ms	remaining: 1.78s
234:	learn: 2.8024651	total: 545ms	remaining: 1.77s
235:	learn: 2.8001866	total: 546ms	remaining: 1.77s
236:	learn: 2.7960300	total: 548ms	remaining: 1.76s
237:	learn: 2.7925484	total: 550ms	remaining: 1.76s
238:	learn: 2.7874919	total: 552ms	remaining: 1.76s
239:	learn: 2.7860204	total: 554ms	remaining: 1.75s
240:	learn: 2.7836560	total: 556ms	remaining: 1.75s
241:	learn: 2.7748793	total: 558ms	remaining: 1.75s
242:	learn: 2.7695842	total: 559ms	remaining: 1.74s
243:	learn: 2.7633050	total: 561ms	remaining: 1.74s
244:	learn: 2.7590949	total: 563ms	remaining: 1.73s
245:	learn: 2.7529092	total: 564ms	remaining: 1.73s
246:	learn: 2.7442432	total: 566ms	remaining: 1.73s
247:	learn: 2.7351036	total: 568ms	remaining: 1.72s
248:	learn: 2.7265004	total: 570ms	remaining: 1.72s
249:	learn: 2.7235972	total: 571ms	remaining: 1.71s
250:	learn: 2.7180154	total: 573ms	remaining: 1.71s
251:	learn: 2.7127266	total: 575ms	remaining: 1.71s
252:	learn: 2.7106757	total: 577ms	remaining: 1.7s
253:	learn: 2.7086002	total: 579ms	remaining: 1.7s
254:	learn: 2.6999626	total: 581ms	remaining: 1.7s
255:	learn: 2.6956169	total: 583ms	remaining: 1.69s
256:	learn: 2.6911159	total: 584ms	remaining: 1.69s
257:	learn: 2.6841780	total: 586ms	remaining: 1.69s
258:	learn: 2.6754937	total: 588ms	remaining: 1.68s
259:	learn: 2.6688489	total: 589ms	remaining: 1.68s
260:	learn: 2.6674179	total: 591ms	remaining: 1.67s
261:	learn: 2.6643966	total: 592ms	remaining: 1.67s
262:	learn: 2.6556558	total: 594ms	remaining: 1.66s
263:	learn: 2.6517990	total: 595ms	remaining: 1.66s
264:	learn: 2.6466433	total: 597ms	remaining: 1.66s
265:	learn: 2.6391334	total: 599ms	remaining: 1.65s
266:	learn: 2.6378822	total: 601ms	remaining: 1.65s
267:	learn: 2.6339478	total: 602ms	remaining: 1.64s
268:	learn: 2.6259617	total: 604ms	remaining: 1.64s
269:	learn: 2.6221867	total: 606ms	remaining: 1.64s
270:	learn: 2.6161270	total: 607ms	remaining: 1.63s
271:	learn: 2.6084571	total: 609ms	remaining: 1.63s
272:	learn: 2.5988946	total: 610ms	remaining: 1.62s
273:	learn: 2.5925183	total: 612ms	remaining: 1.62s
274:	learn: 2.5864000	total: 614ms	remaining: 1.62s
275:	learn: 2.5823892	total: 615ms	remaining: 1.61s
276:	learn: 2.5770780	total: 617ms	remaining: 1.61s
277:	learn: 2.5704865	total: 618ms	remaining: 1.6s
278:	learn: 2.5662409	total: 620ms	remaining: 1.6s
279:	learn: 2.5583341	total: 621ms	remaining: 1.6s
280:	learn: 2.5508152	total: 623ms	remaining: 1.59s
281:	learn: 2.5433359	total: 624ms	remaining: 1.59s
282:	learn: 2.5356058	total: 626ms	remaining: 1.59s
283:	learn: 2.5344329	total: 628ms	remaining: 1.58s
284:	learn: 2.5292140	total: 630ms	remaining: 1.58s
285:	learn: 2.5238389	total: 632ms	remaining: 1.58s
286:	learn: 2.5192307	total: 634ms	remaining: 1.57s
287:	learn: 2.5112275	total: 635ms	remaining: 1.57s
288:	learn: 2.5055356	total: 637ms	remaining: 1.57s
289:	learn: 2.4979134	total: 638ms	remaining: 1.56s
290:	learn: 2.4959680	total: 640ms	remaining: 1.56s
291:	learn: 2.4907062	total: 642ms	remaining: 1.56s
292:	learn: 2.4854088	total: 643ms	remaining: 1.55s
293:	learn: 2.4835600	total: 645ms	remaining: 1.55s
294:	learn: 2.4803527	total: 647ms	remaining: 1.54s
295:	learn: 2.4759210	total: 648ms	remaining: 1.54s
296:	learn: 2.4741363	total: 650ms	remaining: 1.54s
297:	learn: 2.4708516	total: 652ms	remaining: 1.53s
298:	learn: 2.4654147	total: 653ms	remaining: 1.53s
299:	learn: 2.4593483	total: 655ms	remaining: 1.53s
300:	learn: 2.4569688	total: 657ms	remaining: 1.52s
301:	learn: 2.4531316	total: 659ms	remaining: 1.52s
302:	learn: 2.4491318	total: 660ms	remaining: 1.52s
303:	learn: 2.4426570	total: 662ms	remaining: 1.51s
304:	learn: 2.4414302	total: 663ms	remaining: 1.51s
305:	learn: 2.4330496	total: 664ms	remaining: 1.51s
306:	learn: 2.4293053	total: 666ms	remaining: 1.5s
307:	learn: 2.4284144	total: 667ms	remaining: 1.5s
308:	learn: 2.4248737	total: 669ms	remaining: 1.5s
309:	learn: 2.4216020	total: 671ms	remaining: 1.49s
310:	learn: 2.4156803	total: 673ms	remaining: 1.49s
311:	learn: 2.4087365	total: 674ms	remaining: 1.49s
312:	learn: 2.4058389	total: 675ms	remaining: 1.48s
313:	learn: 2.4000246	total: 677ms	remaining: 1.48s
314:	learn: 2.3983115	total: 678ms	remaining: 1.47s
315:	learn: 2.3968815	total: 680ms	remaining: 1.47s
316:	learn: 2.3899025	total: 681ms	remaining: 1.47s
317:	learn: 2.3847267	total: 683ms	remaining: 1.47s
318:	learn: 2.3777159	total: 685ms	remaining: 1.46s
319:	learn: 2.3708809	total: 687ms	remaining: 1.46s
320:	learn: 2.3699701	total: 688ms	remaining: 1.46s
321:	learn: 2.3634678	total: 690ms	remaining: 1.45s
322:	learn: 2.3597007	total: 691ms	remaining: 1.45s
323:	learn: 2.3570387	total: 693ms	remaining: 1.45s
324:	learn: 2.3556327	total: 694ms	remaining: 1.44s
325:	learn: 2.3529438	total: 696ms	remaining: 1.44s
326:	learn: 2.3494613	total: 697ms	remaining: 1.43s
327:	learn: 2.3482877	total: 699ms	remaining: 1.43s
328:	learn: 2.3446632	total: 700ms	remaining: 1.43s
329:	learn: 2.3373965	total: 702ms	remaining: 1.42s
330:	learn: 2.3301862	total: 703ms	remaining: 1.42s
331:	learn: 2.3257227	total: 705ms	remaining: 1.42s
332:	learn: 2.3204089	total: 706ms	remaining: 1.41s
333:	learn: 2.3151909	total: 708ms	remaining: 1.41s
334:	learn: 2.3104031	total: 709ms	remaining: 1.41s
335:	learn: 2.3063674	total: 712ms	remaining: 1.41s
336:	learn: 2.3049612	total: 714ms	remaining: 1.41s
337:	learn: 2.3026863	total: 716ms	remaining: 1.4s
338:	learn: 2.3010854	total: 717ms	remaining: 1.4s
339:	learn: 2.2944341	total: 719ms	remaining: 1.4s
340:	learn: 2.2891833	total: 721ms	remaining: 1.39s
341:	learn: 2.2877765	total: 722ms	remaining: 1.39s
342:	learn: 2.2828470	total: 723ms	remaining: 1.38s
343:	learn: 2.2816071	total: 725ms	remaining: 1.38s
344:	learn: 2.2749148	total: 727ms	remaining: 1.38s
345:	learn: 2.2710435	total: 729ms	remaining: 1.38s
346:	learn: 2.2676695	total: 730ms	remaining: 1.37s
347:	learn: 2.2646977	total: 732ms	remaining: 1.37s
348:	learn: 2.2610832	total: 733ms	remaining: 1.37s
349:	learn: 2.2577558	total: 735ms	remaining: 1.36s
350:	learn: 2.2544741	total: 737ms	remaining: 1.36s
351:	learn: 2.2492885	total: 739ms	remaining: 1.36s
352:	learn: 2.2460586	total: 740ms	remaining: 1.36s
353:	learn: 2.2432005	total: 742ms	remaining: 1.35s
354:	learn: 2.2394120	total: 744ms	remaining: 1.35s
355:	learn: 2.2347844	total: 745ms	remaining: 1.35s
356:	learn: 2.2287142	total: 747ms	remaining: 1.34s
357:	learn: 2.2273614	total: 748ms	remaining: 1.34s
358:	learn: 2.2248948	total: 750ms	remaining: 1.34s
359:	learn: 2.2183709	total: 752ms	remaining: 1.34s
360:	learn: 2.2156128	total: 753ms	remaining: 1.33s
361:	learn: 2.2142479	total: 755ms	remaining: 1.33s
362:	learn: 2.2118295	total: 756ms	remaining: 1.33s
363:	learn: 2.2110104	total: 758ms	remaining: 1.32s
364:	learn: 2.2082014	total: 759ms	remaining: 1.32s
365:	learn: 2.2071544	total: 761ms	remaining: 1.32s
366:	learn: 2.2054768	total: 763ms	remaining: 1.31s
367:	learn: 2.1992774	total: 764ms	remaining: 1.31s
368:	learn: 2.1985162	total: 766ms	remaining: 1.31s
369:	learn: 2.1977863	total: 767ms	remaining: 1.31s
370:	learn: 2.1951917	total: 769ms	remaining: 1.3s
371:	learn: 2.1918650	total: 771ms	remaining: 1.3s
372:	learn: 2.1892304	total: 772ms	remaining: 1.3s
373:	learn: 2.1829168	total: 774ms	remaining: 1.29s
374:	learn: 2.1790765	total: 776ms	remaining: 1.29s
375:	learn: 2.1738452	total: 777ms	remaining: 1.29s
376:	learn: 2.1726300	total: 779ms	remaining: 1.29s
377:	learn: 2.1660661	total: 780ms	remaining: 1.28s
378:	learn: 2.1619821	total: 782ms	remaining: 1.28s
379:	learn: 2.1566900	total: 783ms	remaining: 1.28s